### ISSUE TITLE
sciebo-share Skript

### ISSUE THREAD

**Issue by Erkinator** [stv0g/snippets#2]
Hey Steffen,

wie gesagt hier das Problem, das manchmal bei der Ausführung des Skripts auftritt, mit dieser Fehlermeldung: 

Traceback (most recent call last):
  File "C:\Users\Grauerwolf94\Desktop\sciebo\neue ordnerstruktur\Elektrotechnik B.Sc. & M.Sc.-Ordner.py", line 210, in <module>
    add_shares(options, oc, shares)
  File "C:\Users\Grauerwolf94\Desktop\sciebo\neue ordnerstruktur\Elektrotechnik B.Sc. & M.Sc.-Ordner.py", line 126, in add_shares
    share = oc.share_file_with_user(options.path, id, perms=options.perms)
  File "build\bdist.win32\egg\owncloud\owncloud.py", line 922, in share_file_with_user
    int(data_el.find('id').text),
ValueError: invalid literal for int() with base 10: 'unknown'

Nach der Fehlermeldung bricht das Skript ab und ich muss es neu starten. Unter welchen Umständen es geschieht, kann ich leider nicht sagen. Es erscheint mir fast schon "zufällig". 

Beste Grüße
Erkan

**Comment by stv0g** [comment]
Hi Erkan,

der Fehler scheint wohl in der Python Bibliothek für Owncloud zu liegen.
Scheinbar benutzt du nicht mehr die aktuellste Version von `pyocclient`.

Die [allerneuste Version](https://github.com/owncloud/pyocclient) ist nicht mehr kompatibel mit meinem Script. Ich müsste das mal anpassen.

**Comment by Erkinator** [comment]
Hey,

willst du das denn anpassen? Wenn nicht, wäre ich schon froh, wenn du mir sagen könntest, wo ich mit der Fehlersuche ansetzen soll.

**Comment by stv0g** [comment]
Hey, sorry ich glaube dafür finde ich momentan keine Zeit.

Um den Fehler zu fixen, müsstest du erstmal das Skript an die neueste Version der pyocclient Bibliothek anpassen. Da hat sich das Interface leicht geändert.

Ich vermute, dass der Fehler bereits in der neuesten Version gefixt wurde.

viele Grüße

**Comment by debalance** [comment]
Jetzt wo ich weiß welche Library für das Skript benötigt wird kann ich mir das bei Gelegenheit auch mal näher ansehen.
